version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Identity/Identity.Api/Dockerfile
    depends_on:
      - postgres
    ports:
       - "10000:8080"  
    networks:
       - ballast_default

  aircraft.api:
    image: ${DOCKER_REGISTRY-}aircraftapi
    build:
      context: .
      dockerfile: src/Aircraft/Aircraft.Api/Dockerfile
    depends_on:
      - postgres
    ports:
       - "10001:8080"  
    networks:
       - ballast_default

  postgres:
    image: postgres:16-alpine
    ports:
       - "5432:5432"
    environment:
       "POSTGRES_PASSWORD": "password"
       "POSTGRES_USER": "postgres"
       "POSTGRES_DB": "postgres"
    volumes:
       - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
       - ballast_default

networks:
  ballast_default:
    name: ballast_default
